export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    OTP_VERIFY_REQUEST: "OTP_VERIFY_REQUEST",
    OTP_VERIFY_SUCCESS: "OTP_VERIFY_SUCCESS",
    OTP_VERIFY_FAILURE: "OTP_VERIFY_FAILURE",

    RESEND_OTP_REQUEST: "RESEND_OTP_REQUEST",
    RESEND_OTP_SUCCESS: "RESEND_OTP_SUCCESS",
    RESEND_OTP_FAILURE: "RESEND_OTP_FAILURE",
    GET_SETTING_SUCCESS: 'GET_SETTING_SUCCESS',

    PASSWORD_UPDATE_REQUEST: "PASSWORD_UPDATE_REQUEST",
    PASSWORD_UPDATE_SUCCESS: "PASSWORD_UPDATE_SUCCESS",
    PASSWORD_UPDATE_FAILURE: "PASSWORD_UPDATE_FAILURE",

    OAUTH_LOGIN_REQUEST: "OAUTH_LOGIN_REQUEST",
    OAUTH_LOGIN_SUCCESS: "OAUTH_LOGIN_SUCCESS",
    OAUTH_LOGIN_FAILURE: "OAUTH_LOGIN_FAILURE",

    CURRENT_USER_REQUEST: "CURRENT_USER_REQUEST",
    CURRENT_USER_SUCCESS: "CURRENT_USER_SUCCESS",
    CURRENT_USER_FAILURE: "CURRENT_USER_FAILURE",
};